version: 2.1

jobs:
  packj-audit:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: python -m venv venv
      - run: source venv/bin/activate
      - run: git clone https://github.com/ossillate-inc/packj
      - run: /usr/local/bin/python -m pip install --upgrade pip
      - run: rm ./packj/.packj.yaml
      - run: ls ./packj -al
      - run: pip install -r ./packj/requirements.txt
      - run:
          name: Audit dependency files with Packj
          command: |
            input=$(echo $DEPENDENCY_FILES | sed 's/,/ /g') 
            input_files=()
            for item in $input
              do
                if [[ $item == *":"* ]]; then
                  pm_name=$(echo $item | cut -f1 -d:)
                  dep_file=$(echo $item | cut -f2 -d:)
                  input_files+=$pm_name":"$path,
                fi
              done
            if [ ! -z input_files ]; then
              input=$(echo $input_files | sed 's/,/ /g')
              python ./packj/main.py audit -f $input 
            fi
    environment:
      DEPENDENCY_FILES: pypi:requirements.txt,npm:package.json

workflows:
  build:
    jobs:
      - packj-audit:
          filters:
            branches:
              only: main
